#!/bin/sh

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
MEDIUM_PATH="/run/live/medium"
RELEASE="lts"

if [ "$1" = "-u" ]; then
    umount $CHROOT/$MEDIUM_PATH
    rm $CHROOT/etc/apt/sources.list || true
    mv $CHROOT/etc/apt/sources.list.orig $CHROOT/etc/apt/sources.list
    mv $CHROOT/etc/apt/sources.list.parrot $CHROOT/etc/apt/sources.list.d/parrot.list
    chroot $CHROOT apt-get update || true
    exit 0
fi

# Remove the base sources, we will configure sources in a later phase
rm -f $CHROOT/etc/apt/sources.list.d/base.list || true

mkdir -p $CHROOT/$MEDIUM_PATH
mount --bind $MEDIUM_PATH $CHROOT/$MEDIUM_PATH
mv $CHROOT/etc/apt/sources.list $CHROOT/etc/apt/sources.list.orig
mv $CHROOT/etc/apt/sources.list.d/parrot.list $CHROOT/etc/apt/sources.list.parrot
echo "deb [trusted=yes] file://$MEDIUM_PATH $RELEASE main" > $CHROOT/etc/apt/sources.list
chroot $CHROOT apt-get update
# Attempt safest way to remove cruft
rmdir $CHROOT/run/live/medium
rmdir $CHROOT/run/live
# Fix KDE Settings
if [ $XDG_CURRENT_DESKTOP ! "KDE" ]; then
	:
else
	echo "/usr/sbin/sddm" > $CHROOT/etc/X11/default-display-manager
	DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true chroot $CHROOT dpkg-reconfigure sddm
fi
# Delete Home
for user in $(cd $CHROOT/home && ls); do
	rm $CHROOT/home/$user/Desktop/README.license
done
exit 0
